apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-casopractico2
  namespace: casopractico2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi