apiVersion: v1
kind: Service
metadata:
  name: svc-casopractico2
  namespace: casopractico2
spec:
  type: LoadBalancer
  selector:
    app: app-casopractico2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80